/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./components/ui/AppLogo.vue')['default']
    AuthCard: typeof import('./components/ui/AuthCard.vue')['default']
    CompanySelector: typeof import('./components/features/CompanySelector.vue')['default']
    ConfirmDialog: typeof import('./components/ui/ConfirmDialog.vue')['default']
    DataTable: typeof import('./components/ui/DataTable.vue')['default']
    DeleteUser: typeof import('./components/features/DeleteUser.vue')['default']
    Heading: typeof import('./components/ui/Heading.vue')['default']
    PageHeader: typeof import('./components/layout/PageHeader.vue')['default']
    Pagination: typeof import('./components/ui/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsLayout: typeof import('./components/layout/SettingsLayout.vue')['default']
    TeamMemberModal: typeof import('./components/features/TeamMemberModal.vue')['default']
    TransactionTable: typeof import('./components/features/TransactionTable.vue')['default']
  }
}
