/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppLogo: typeof import('./components/AppLogo.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    DeleteUser: typeof import('./components/DeleteUser.vue')['default']
    Heading: typeof import('./components/Heading.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsLayout: typeof import('./components/SettingsLayout.vue')['default']
  }
}
