/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/confirm-password': RouteRecordInfo<'/auth/confirm-password', '/auth/confirm-password', Record<never, never>, Record<never, never>>,
    '/auth/forgot-password': RouteRecordInfo<'/auth/forgot-password', '/auth/forgot-password', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/register': RouteRecordInfo<'/auth/register', '/auth/register', Record<never, never>, Record<never, never>>,
    '/auth/reset-password': RouteRecordInfo<'/auth/reset-password', '/auth/reset-password', Record<never, never>, Record<never, never>>,
    '/auth/two-factor-challenge': RouteRecordInfo<'/auth/two-factor-challenge', '/auth/two-factor-challenge', Record<never, never>, Record<never, never>>,
    '/auth/verify-email': RouteRecordInfo<'/auth/verify-email', '/auth/verify-email', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/settings/password': RouteRecordInfo<'/settings/password', '/settings/password', Record<never, never>, Record<never, never>>,
    '/settings/profile': RouteRecordInfo<'/settings/profile', '/settings/profile', Record<never, never>, Record<never, never>>,
    '/settings/two-factor': RouteRecordInfo<'/settings/two-factor', '/settings/two-factor', Record<never, never>, Record<never, never>>,
    '/team-members/': RouteRecordInfo<'/team-members/', '/team-members', Record<never, never>, Record<never, never>>,
    '/transactions/': RouteRecordInfo<'/transactions/', '/transactions', Record<never, never>, Record<never, never>>,
    '/wallets/': RouteRecordInfo<'/wallets/', '/wallets', Record<never, never>, Record<never, never>>,
    '/wallets/create': RouteRecordInfo<'/wallets/create', '/wallets/create', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/auth/confirm-password.vue': {
      routes: '/auth/confirm-password'
      views: never
    }
    'src/pages/auth/forgot-password.vue': {
      routes: '/auth/forgot-password'
      views: never
    }
    'src/pages/auth/login.vue': {
      routes: '/auth/login'
      views: never
    }
    'src/pages/auth/register.vue': {
      routes: '/auth/register'
      views: never
    }
    'src/pages/auth/reset-password.vue': {
      routes: '/auth/reset-password'
      views: never
    }
    'src/pages/auth/two-factor-challenge.vue': {
      routes: '/auth/two-factor-challenge'
      views: never
    }
    'src/pages/auth/verify-email.vue': {
      routes: '/auth/verify-email'
      views: never
    }
    'src/pages/dashboard.vue': {
      routes: '/dashboard'
      views: never
    }
    'src/pages/settings/password.vue': {
      routes: '/settings/password'
      views: never
    }
    'src/pages/settings/profile.vue': {
      routes: '/settings/profile'
      views: never
    }
    'src/pages/settings/two-factor.vue': {
      routes: '/settings/two-factor'
      views: never
    }
    'src/pages/team-members/index.vue': {
      routes: '/team-members/'
      views: never
    }
    'src/pages/transactions/index.vue': {
      routes: '/transactions/'
      views: never
    }
    'src/pages/wallets/index.vue': {
      routes: '/wallets/'
      views: never
    }
    'src/pages/wallets/create.vue': {
      routes: '/wallets/create'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
